version: '3.8'

services:
  mysql:
    image: shashank092/revtickets-mysql:latest
    container_name: revtickets-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: revticketsnew
    networks:
      - revtickets-network

  mongodb:
    image: shashank092/revtickets-mongodb:latest
    container_name: revtickets-mongodb
    ports:
      - "27017:27017"
    networks:
      - revtickets-network

  backend:
    image: shashank092/revtickets-backend:latest
    container_name: revtickets-backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - mongodb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/revticketsnew
      SPRING_DATA_MONGODB_HOST: mongodb
    networks:
      - revtickets-network

  frontend:
    image: shashank092/revtickets-frontend:latest
    container_name: revtickets-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - revtickets-network

networks:
  revtickets-network:
    driver: bridge
